DROP TABLE IF EXISTS sensors;
DROP TABLE IF EXISTS actuators;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS images;

CREATE TABLE sensors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    device TEXT NOT NULL,
    reading TEXT NOT NULL
);

CREATE TABLE actuators (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    device TEXT NOT NULL,
    reading TEXT NOT NULL
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    device TEXT NOT NULL,
    reading TEXT NOT NULL
);

CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filename TEXT NOT NULL,
    extension TEXT NOT NULL
);
